
const functions = require("../translator/functions")

test("filterInvalidFunctions returns a valid function", () => {
    const rawFunction = "ActionMarker_StartAction( String name ) RETURNS:  =>Start the given action marker's FX."
    const actual = functions.filterInvalidFunctions([rawFunction])
    const expected = [rawFunction]

    expect(actual).toEqual(expected)
})


test("filterInvalidFunctions skips empty lines", () => {
    const rawFunction = ""
    const actual = functions.filterInvalidFunctions([rawFunction])
    const expected = []

    expect(actual).toEqual(expected)
})

test("filterInvalidFunctions skips lines starting with #", () => {
    const rawFunction = "# GENERATED BY WSCITE_API.XSL   DO NOT EDIT BY HAND!"
    const actual = functions.filterInvalidFunctions([rawFunction])
    const expected = []

    expect(actual).toEqual(expected)
})